### ISSUE TITLE
Getting error with neoformat when using uncrustify formatter for c

### ISSUE THREAD

**Issue by asher-gh** [Pocco81/TheSupercalifragilisticexpialidociousDots#3]
Getting this error when using `NeoFormat uncrustify` in c.
```
NeoFormat: formatters uncrustify failed to run
```
I'm able to successfully use `uncrustify` in shell. Other formatters for c `astyle` and `clangformat` are also working fine.

I think that I need to define the formatter with specific arguments for `stdout`. Can you help me with that?

**Comment by asher-gh** [comment]
Solved. Anyone facing issue when using `uncrustify` with C, Add this to `globals` variable in `~/.config/nvim/lua/nvd_settings.lua` 
```lua
			neoformat_c_uncrustify = {
			     exe= "uncrustify",
			     args= {"-q", "-l C","-f"},
			},
			neoformat_enabled_c = {"uncrustify"}

```

**Comment by Pocco81** [comment]
If I'm honest with you, I never thought about using the `globals` table for configuring stuff other that vim settings that required globals in general. Great tip :)

**Comment by asher-gh** [comment]
Do you think that configuring this way could have an impact on performance? If so should I configure this directly in the extension.lua?

**Comment by Pocco81** [comment]
Oh no not at all, you are just instantiating some variables. Setting them up under `extension.lua` is the same as setting them up  in the main config file.

The only things that should affect performance (although not significantly) are the ones under `system` (that's why they are set to `nil` by default) and checking health. Why? Well:

![image](https://user-images.githubusercontent.com/58336662/131266170-3c1b1205-d84d-4475-bc59-1bfc2dd30685.png)

This needs to fetch system info, because we are setting a relative path, relative to the OS. Jnlike setting it to an absolute path (e.g. `/tmp/data/`).

![image](https://user-images.githubusercontent.com/58336662/131266191-9e8f36e3-7469-4933-bb68-e6b294d6a681.png)

Same story here. You are evaluating if this stuff exists in your machine, which of course takes time. I'd only recommend using the health module after installing NVDope, for obvious reasons. As well as after updating it.

**Comment by asher-gh** [comment]
Thanks for such great explanation
